### ISSUE TITLE
Broken context command for arcs

### ISSUE THREAD

**Issue by KimBruce** [gracelang/objectdraw#23]
Something has changed with the context object used in objectdraw.  If I try to invoke 
```
filledOvalAt (160 @ 50) size (100 @ 200) on (canvas)
```
(or anything else drawing ovals or arcs) I get the following error message:
```
NoSuchMethod on line 1642 of objectdraw: no method 'arc(_,_,_,_,_)' on wrappedDomObject DOMObject([object CanvasRenderingContext2D]).
  raised at wrappedDomObject.arc(_,_,_,_,_) at line 1642 of objectdraw
  called from module.draw(_,_,_,_) at line 1171 of objectdraw
  called from execution environment.
1641:         ctx.scale (width / 2, height / 2)
1642:         ctx.arc (0, 0, 1, 0, 2*pi)
1643:         ctx.restore
```
This used to work, so somehow something changed in the dom implementation for Javascript.

**Comment by petercowal** [comment]
The change occurred with the introduction of betterNames.  Since Grace methods need to specify the number of parameters of a method, problems arise when `dom.js` tries to wrap Javascript methods (which can always take an arbitrary number of parameters).  The current approach is to use numerous Grace methods to wrap a single Javascript method (e.g. `arc` -> `arc`, `arc(1)`, `arc(2)`...), and the problem's being caused by the arbitrarily set limit to 4 parameters.  I'll push a fix to minigrace as soon as possible.
